// Types
import type { Metadata } from 'next'

// Fonts
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

// Vercel
import { Analytics } from '@vercel/analytics/react'

// Styles
import '@/styles/main.scss'

// Components
import Footer from '@/components/Footer'
import Navigation from '@/components/Navigation'

// Providers
import Providers from './providers'

export const metadata: Metadata = {
	title: 'Brandon Bridges',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Providers>
					<Navigation />
					{children}
					<Footer />
					<Analytics />
				</Providers>
			</body>
		</html>
	)
}
